### ISSUE TITLE
daddylive not working

### ISSUE THREAD

**Issue by austreams** [mrgsi/repository.glive#11]

**Comment by mrgsi** [comment]
Yes, I've noticed that and really not surprised. The way the add-on was originally coded makes it unstable. The Crew tries to maintain it, but they can take several weeks before pushing out an update. There are alternative ways of getting Daddylive channels that are more stable and I just started looking into those. One that is currently in the G-Sports repo is "Gratis" from the funstersplace repo. It provides the Daddylive channels using a different approach in coding which seems more stable and is currently working.

**Comment by ccrn123** [comment]
Unable to load the Crew- no zip file. Tried:
https://team-crew.github.io
http://team-crew.github.io
added a / at the end of these as well

rebuilt kodi x 3
Tried adding the crew x6

new to kodi. Need help. Love Daddy Live.
Cindy

**Comment by mrgsi** [comment]
Yep, the Crew screwed up their link for that so until it's fixed it won't work via the file manager. Your other options would be to either download the zip file, then install from zip using https://github.com/team-crew/team-crew.github.io/raw/master/repository.thecrew-0.3.5.zip or you can install my g-source repo and get the crew repo by going into my repo under Add-on repository. I have most repositories listed there. I also ALWAYS have the latest Daddylive add-on in my repos, but the Crew hasn't fixed it yet so we are just waiting on them. In the mean time you can install "Gratis" which has Daddylive built in and is working.

**Comment by ccrn123** [comment]
Thank you SO much!!!!…. too new to figure this out on my own.🥹CindySent from my iPhoneOn Feb 12, 2024, at 11:03 AM, G-Man ***@***.***> wrote:﻿
Yep, the Crew screwed up their link for that so until it's fixed it won't work via the file manager. Your other options would be to either download the zip file, then install from zip using https://github.com/team-crew/team-crew.github.io/raw/master/repository.thecrew-0.3.5.zip or you can install my g-source repo and get the crew repo by going into my repo under Add-on repository. I have most repositories listed there. I also ALWAYS have the latest Daddylive add-on in my repos, but the Crew hasn't fixed it yet so we are just waiting on them. In the mean time you can install "Gratis" which has Daddylive built in and is working.

**Comment by mrgsi** [comment]
Not a problem. There are also some good reddit forums you can use to dig deep into Kodi. https://www.reddit.com/r/Kodi_Helpers/ is one I help moderate and https://www.reddit.com/r/Addons4Kodi/ has a lot of users. Both are third party add-on friendly (meaning not officially supported by Kodi). Trouble shooting can be very time consuming with Kodi since there are so many things that can go wrong. Just make sure you use a premium service like real-debrid.com for TV and movies. For about $5 a month it makes Kodi almost limitless in quality streaming, network and dvd content. I haven't left the house in over 2 years! Just kidding LOL

**Comment by ccrn123** [comment]
G-man, You made my day. G-source loaded…. Gratis works.  I do have NordVPN, Trakt and Premiumize…. thanks for the advise.  Cindy

**Comment by ccrn123** [comment]
Pls recheck Gratis- both Live Channel and Live Sport started “playback failed” about 2pm today. Uninstalled and reinstalled both YouTube and Gratis. Speed test good for 1080. Caches cleared with GUI wizard. Running out of reading more articles on the subject. Thank you again. Cindy

**Comment by mrgsi** [comment]
Yes, I just checked and Gratis isn't working for daddylive. Unfortunately, it's a common problem for any add-on pulling daddylive links. We will probably see an update in a few days.
