### ISSUE TITLE
Canada channels don't work

### ISSUE THREAD

**Issue by deputydoobie** [mrgsi/repository.glive#7]
Can't get Canadian channels to work, persisting issue

**Comment by mrgsi** [comment]
I can check it, but need to know which add-on you are having the problem with. MegaIPTV is good. You can get some links in tvOne112 and tvOne1112. Are you looking for a specific channel? For sports I'd use Daddylive TSN and Sportsnet channels. For CBC Live, I'd use the CBC add-on from the Kodi repo. It will ask you for an account name, but just ignore that and go to the Live channels. Your location may be a factor as well. I am in Canada so can only test from my own perspective, eh. lol

**Comment by deputydoobie** [comment]
Specifically I'm looking for channels like ytv to work via tvone111 I have it running through tvone1112 and rntv I just would like to have a backups

**Comment by mrgsi** [comment]
Unfortunately RACC hasn't updated tvOne111 since 2021.  tvOne1112 is the same way, you are just lucky YTV still works. I'm always on the lookout for new IPTV add-ons and links so if I get a good one it will be added to the list.

**Comment by deputydoobie** [comment]
Oh snap well thank you anyway my dude
