### ISSUE TITLE
How i put subtitles in thetvapp

### ISSUE THREAD

**Issue by farsafar** [mrgsi/repository.glive#8]
i need the subtitles but i dont know how to put

**Comment by mrgsi** [comment]
Go into Kodi Settings, then into Player. In there I went into languages and turned on "Prefer subtitles for hearing impaired". Then I went into Subtitles and turned on "Enable parsing for Closed Caption". Then I went back and tried playing a stream. From the on-screen player controls I clicked on the Subtitles icon then switched on subtitles. Now the videos display Closed Caption.
